Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2023-07, with the labels that each got.

#6 Feature ci pipeline 01
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  .gitignore
Labels: Sprint 1

#11 Feature ci jest 02
  .github/dependabot.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  .gitignore
  docs
  jest.config.js
  package-lock.json
  package.json
  tests/mocks/math.ts
  tests/unit/math.test.ts
Labels: Sprint 1

#13 Pushing the requested change to ignore the .idea folder in intellij
  .gitignore
Labels: Sprint 2

#10 User auth-5-ua landing page-01
  .gitignore
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/forgot-password/page.tsx
  app/api/auth/profile/page.tsx
  app/api/auth/sign-in/page.tsx
  app/api/auth/sign-up/page.tsx
  app/api/auth/users/route.ts
  app/layout.tsx
  app/page.tsx
  components/InputFields.tsx
  components/Navbar.tsx
  components/SessionProvider.tsx
  package-lock.json
  package.json
  styles/Home.module.css
  styles/globals.css
Labels: Sprint 1

#22 belindas-closet_3 _21_ create-pr-template
  pull_request_template.md
Labels: documentation, Sprint 3

#38 Pm 37 issue templates 01
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, Sprint 4

#35 added naming convention
  pull_request_template.md
Labels: enhancement, Sprint 4

#34 Belindas-closet-nextjs-4-34-add-product-page-link
  app/api/auth/product-page/page.module.css
  app/api/auth/product-page/page.tsx
  components/Navbar.tsx
Labels: Sprint 4

#43 added new_branch.yml
  .github/workflows/new_branch.yml
Labels: Sprint 2

#46 Refactored CSS module
  app/api/auth/forgot-password/forgot-password-page.module.css
  app/api/auth/forgot-password/page.tsx
  app/api/auth/profile/page.tsx
  app/api/auth/sign-in/page.tsx
  app/api/auth/sign-in/signin-page.module.css
  app/api/auth/sign-up/page.tsx
  app/api/auth/sign-up/signup-page.module.css
  app/login-page.module.css
  app/page.tsx
Labels: enhancement, Sprint 1

#48 Belindas-closet-nextjs-4-3-ci-pipeline
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/keeps-staging-in-sync.yml
  .github/workflows/main.yml
  .github/workflows/new_branch.yml
  .github/workflows/pull-request.yml
  .github/workflows/staging.yml
  .gitignore
Labels: Sprint 4
