Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2023-08, with the labels that each got.

#47 Belindas-closet-nextjs-4-41-add-a-product-functionality
  app/api/auth/product-page/page.tsx
Labels: Sprint 4

#53 belindas-closet-nextjs_4_52_edit-issue-template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug, Sprint 4

#61 Belinda-NextJS_4_2_deploy-web-online
  .gcloudignore
  app.yaml
  app/api/auth/profile/page.tsx
  next.config.js
  package.json
  tsconfig.json
Labels: Sprint 4

#56 Feat 42 web user next auth step 1
  lib/db.ts
  models/userModel.ts
  package-lock.json
  package.json
Labels: Sprint 4

#69 Feature 60 web user auth 01
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/users/route.ts
  lib/db.ts
Labels: enhancement, Sprint 5
