Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2024-03, with the labels that each got.

#246 belinda-nextjs-bug-245-fixing-sidebar
  components/CategoryDropDownMenu.tsx
  components/Navbar.tsx
Labels: bug

#259 belindas-closet-nextjs_4_258_delete_find_stale_templates
  pull_request_template.md
Labels: bug, Sprint 4

#252 belinda-nextjs-04-251-implement-change-password-function-01
  app/auth/change-password-page/page.tsx
Labels: Sprint 4

#248 Belinda_NextJS_Sprint_3_244_Transition_forget_password_page_to _MUI
  app/auth/forgot-password/page.tsx
Labels: enhancement, Sprint 3

#260 belindas-closet-nextjs_4_254_edit-user-role-functionality
  app/auth/sign-in/page.tsx
  components/EditUserRoleDialog.tsx
Labels: enhancement, Sprint 4

#261 belindas-closet-nextjs_4_256_buttons-functionality
  app/auth/sign-in/page.tsx
  app/category-page/[categoryId]/page.tsx
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
  app/category-page/[categoryId]/products/[productId]/page.tsx
  components/ConfirmArchiveDialog.tsx
  components/ConfirmDeleteDialog.tsx
  package-lock.json
Labels: enhancement, Sprint 4

#263 belinda-nextjs-04-262-update-signup-page-01
  app/auth/sign-up/page.tsx
  app/auth/sign-up/signup-page.module.css
  components/ErrorAlert.tsx
  components/SuccessAlert.tsx
Labels: Sprint 4

#271 belinda-nextjs-feature-194-update-to-mui
  app/add-product-page/page.tsx
  app/donation-info/page.tsx
  app/layout.tsx
  app/page.tsx
  app/theme/theme.tsx
  components/CustomCardContent.tsx
Labels: Sprint 4

#270 belinda-nextjs-bug-269-error-message-display-inconsistent
  app/auth/change-password-page/page.tsx
Labels: bug

#272 belindas-closet-nextjs_4_265_edit-functionality-button-visibility
  app/category-page/[categoryId]/page.tsx
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
  app/category-page/[categoryId]/products/[productId]/page.tsx
  components/ConfirmArchiveDialog.tsx
  components/ConfirmDeleteDialog.tsx
  components/EditProductDialog.tsx
  components/Input.tsx
  components/InputSelect.tsx
Labels: enhancement, Sprint 4

#273 belindas-closet-nextjs_4_194_standardize_wrapper
  app/add-product-page/page.tsx
  app/admin-page/page.tsx
  app/auth/change-password-page/page.tsx
  app/auth/forgot-password/page.tsx
  app/auth/reset-password-page/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
  app/category-page/[categoryId]/page.tsx
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
  app/category-page/[categoryId]/products/[productId]/page.tsx
  app/creator-page/page.tsx
  app/donation-info/page.tsx
  app/edit-user-role-page/page.tsx
  app/layout.tsx
  app/page.tsx
  app/profile/page.tsx
  components/ProductCard.tsx
  components/WrapperDiv.tsx
Labels: Sprint 4
