Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2024-04, with the labels that each got.

#275 belindas-closet-nextjs-274-fix-nextjs-templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/pull_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: bug

#287 belinda-closet-nextjs_5_281_responsive-menu-fields
  app/add-product-page/page.tsx
Labels: enhancement, Sprint 5

#289 belindas-closet-nextjs_5_278_add-product-button
  app/admin-page/page.tsx
Labels: Sprint 5

#290 belinda-closet-nextjs_5_279_mission-page-with-route
  app/mission-page/page.tsx
  components/Navbar.tsx
Labels: Sprint 5, USER STORY

#298 belinda-nextjs-05-282-image-upload-feedback
  app/add-product-page/page.tsx
Labels: Sprint 5

#305 belindas-closet-nextjs_5_293_edit-user-role-button-and-page-styling
  app/admin-page/page.tsx
Labels: enhancement, Sprint 5

#285 belindas-closet-nextjs-contact-page
  app/admin-page/page.tsx
  app/contact-page/page.tsx
  components/Navbar.tsx
  package-lock.json
Labels: Sprint 5

#297 belinda-nextjs-04-235-add-profile-menu-to-navbar
  app/auth/sign-in/page.tsx
  components/AuthProfileMenu.tsx
  components/Navbar.tsx
Labels: Sprint 4

#304 belindas-closet-nextjs_5_294_Dashboard Page
  app/dashboard/page.tsx
  components/Navbar.tsx
Labels: enhancement, Sprint 5

#313 belinda-nextjs-chore-remove-unused-authentication-next-server
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/users/route.ts
Labels: Sprint 5

#317 belindas-closet-nextjs_5_315_Dashboard Page
  components/Navbar.tsx
Labels: enhancement, Sprint 5
