Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2024-02, with the labels that each got.

#192 belindas-closet-nextjs_185_1_product-detail-page
  app/category-page/[categoryId]/page.tsx
  app/category-page/[categoryId]/products/[productId]/page.tsx
  tsconfig.json
Labels: enhancement, Sprint 1

#193 belindas-closet-nextjs-2-180-added-buttons-to-creator-page
  app/creator-page/page.tsx
Labels: enhancement, Sprint 2

#201 Belindas-closet-nextjs-2-200-create-templates-for-nextjs
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/pull_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: Sprint 2

#190 Belindas-closet-nextjs-2-199-add-buttons-to-admin-page
  app/admin-page/page.tsx
Labels: Sprint 2

#197 belindas-closet-nextjs_2_196_link-product-categories-in-dropdown
  components/Navbar.tsx
Labels: Sprint 2

#206 belindas-closet-nextjs-2-205-add-front-matter-to-nextjs
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/pull_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: Sprint 2

#203 belinda-nextjs_enhancement_202_display_products_in_categories
  app/category-page/[categoryId]/page.module.css
  app/category-page/[categoryId]/page.tsx
  app/category-page/page.tsx
Labels: enhancement

#191 Belinda_NextJS_Sprint_1_166_Password_Toggle
  app/auth/sign-up/page.tsx
  components/InputFields.tsx
Labels: Sprint 1

#213 Belindas-closet-nextjs-2-209-MUI-main-content
  app/home.module.css
  app/page.tsx
  components/CategoryCard.tsx
  components/CustomCardContent.tsx
  package-lock.json
  package.json
Labels: enhancement, Sprint 2

#221 Belindas-closet-nextjs-3-214-Signup-Page
  app/auth/sign-up/page.tsx
Labels: enhancement

#218 belindas-closet-nextjs_2_208_add-product-card-component
  app/category-page/[categoryId]/page.module.css
  app/category-page/[categoryId]/page.tsx
  components/ProductCard.tsx
  package-lock.json
Labels: enhancement, Sprint 2

#223 belinda-nextjs-03-220-reset-password-page
  app/auth/reset-password-page/page.tsx
  app/layout.tsx
  app/theme/theme.tsx
  src/react-app-env.d.ts
Labels: Sprint 3

#226 belinda-nextjs-225-delete_archive_buttons-01
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
  app/category-page/[categoryId]/products/[productId]/page.tsx
Labels: Sprint 3

#229 belinda-nextjs-03-228-add-edit-user-role-page
  app/edit-user-role-page/page.tsx
  components/EditUserRoleDialog.tsx
  components/UserCard.tsx
Labels: Sprint 3

#232 belinda-nextjs-03-231-modify-add-components-product-page
  app/auth/sign-in/page.tsx
  app/category-page/[categoryId]/page.module.css
  app/category-page/[categoryId]/page.tsx
  components/ProductCard.tsx
Labels: Sprint 3

#236 belinda-nextjs-03-210-update-the-navbar
  components/CategoryDropDownMenu.tsx
  components/Navbar.tsx
Labels: Sprint 3

#238 belinda-nextjs-03-211-general-page-styling-to-MUI
  app/layout.tsx
  app/page.tsx
  app/theme/theme.tsx
Labels: enhancement, Sprint 3

#240 belinda-nextjs-bug-239-loading-individual-product-page
  app/category-page/[categoryId]/products/[productId]/page.tsx
Labels: bug

#241 update sign in page
  app/auth/sign-in/page.tsx
  app/auth/sign-in/signin-page.module.css
Labels: Sprint 3
