Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2024-08, with the labels that each got.

#520 belindas-closet-nextjs_10_511_bug-fix-unit-test-errors-signup-page
  app/contact-page/page.tsx
  jest.setup.js
  package-lock.json
  package.json
  tests/unit/contact-page/contactpage.test.tsx
  tests/unit/creator-page/page.test.tsx
Labels: dependencies, Sprint 10

#525 Chore belindas nextjs update api evironment
  .env.sample
  app/add-product-page/page.tsx
  app/archived-products-page/page.tsx
  app/auth/change-password-page/page.tsx
  app/auth/reset-password-page/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
  app/category-page/[categoryId]/page.tsx
  app/category-page/[categoryId]/products/[productId]/page.tsx
  app/category-page/all-products/page.tsx
  app/edit-user-role-page/page.tsx
  app/profile/page.tsx
  components/ConfirmArchiveDialog.tsx
  components/ConfirmDeleteDialog.tsx
  components/EditProductDialog.tsx
  components/EditUserRoleDialog.tsx
  components/ProductCard.tsx
  next.config.js
Labels: enhancement

#529 belindas-closet-nextjs-10-528-add-button-redirect-admin-profile-page
  app/admin-page/page.tsx
  tests/unit/admin-page/admin.test.tsx
Labels: Sprint 10

#534 belindas-closet-nextjs_10_533_dashboard-page
  app/dashboard/page.tsx
  public/belinda-images/nsc_mascot.png
  tests/unit/dashboard-page/page.test.tsx
Labels: enhancement, Sprint 10

#535 belindas_closet_nextjs_11_532_add-profile-button-to-creator-page
  app/creator-page/page.tsx
Labels: Sprint 10

#538 belindas-closet-nextjs_11_531_remove-archive-button-archived-products-page
  app/archived-products-page/page.tsx
  components/ProductCard.tsx
Labels: Sprint 10
