Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2024-06, with the labels that each got.

#415 belinda-nextjs-refactor-410-add-belinda-designs
  app/auth/change-password-page/page.tsx
  app/auth/reset-password-page/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
  app/category-page/[categoryId]/page.tsx
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
  app/page.tsx
  components/CategoryImages.tsx
  components/Navbar.tsx
  public/belinda-images/google_play.png
  public/belinda-images/header_logo.png
  public/belinda-images/logo.png
  public/belinda-images/nsc_mascot_green_cropped.png
  public/categories-images/dark-images/accessories.png
  public/categories-images/dark-images/casual.png
  public/categories-images/dark-images/dress.png
  public/categories-images/dark-images/jacket.png
  public/categories-images/dark-images/pants.png
  public/categories-images/dark-images/shirt.png
  public/categories-images/dark-images/shoe.png
  public/categories-images/dark-images/skirt.png
  public/categories-images/dark-images/suit.png
  public/categories-images/light-images/accessories.png
  public/categories-images/light-images/casual.png
  public/categories-images/light-images/dress.png
  public/categories-images/light-images/jacket.png
  public/categories-images/light-images/pants.png
  public/categories-images/light-images/shirt.png
  public/categories-images/light-images/shoe.png
  public/categories-images/light-images/skirt.png
  public/categories-images/light-images/suit.png
Labels: Sprint 7

#420 belinda-nextjs-bug-missing-current-password-field
  app/auth/change-password-page/page.tsx
Labels: bug

#425 belindas-closet-nextjs-7-422-admin-page-unit-test
  .vscode/launch.json
  tests/admin.test.tsx
Labels: Sprint 7

#418 belindas-closet-nextjs_Sprint7_issue#403_UnitTest:Creatorpage
  tests/unit/creator-page/page.test.tsx
Labels: Sprint 7

#427 Navbar and toggle button adjustment
  components/Navbar.tsx
  package-lock.json
  package.json
Labels: Sprint 8

#433 belinda-nextjs-chore-432-refactor-product-card
  app/category-page/[categoryId]/page.tsx
  components/ProductCard.tsx
Labels: enhancement

#430 belindas-closet-nextjs_8_429_create-all-products-page
  app/category-page/all-products/page.tsx
Labels: Sprint 8

#431 Belinda_Nextjs_424_Contact_Us_Page_Sprint8
  app/contact-page/page.tsx
Labels: Sprint 8

#443 belindas-closet-nextjs-8-442-sign-up-page-unit-test-bug-repair
  app/auth/sign-up/page.tsx
  tests/unit/auth/sign-up/page.test.tsx
Labels: bug, Sprint 8

#451 Belindas-Closet-nextjs-8-contact-page-unit-test
  tests/unit/contact-page/contactpage.test.tsx
Labels: Sprint 8

#453 Belindas-Closet-nextjs-8-452-mission-page-unit-test
  tests/unit/mission-page/missionpage.test.tsx
Labels: Sprint 8

#396 UI-Dashboard
  app/dashboard/page.tsx
Labels: Sprint 7

#460 belindas-closet-nextjs_8_448_simplify-product-description
  app/category-page/[categoryId]/page.tsx
Labels: enhancement, Sprint 8
