Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2024-01, with the labels that each got.

#131 belinda-nextjs-01-130-modify-fronend-port
  package.json
Labels: Sprint 1

#148 Belinda_Nextjs_Sprint_1_141_FirstName_LastName
  app/auth/sign-up/page.tsx
Labels: Sprint 1

#143 belinda-nextjs-01-137-homepage-category-cards
  app/category-page/page.tsx
  app/home.module.css
  app/page.tsx
  components/CategoryCard.tsx
  package-lock.json
  package.json
Labels: Sprint 1

#150 belindas-closet-nextjs-1-149-add-material-UI-icons-and-roboto-font
  package-lock.json
  package.json
  styles/globals.css
Labels: dependencies

#147 belindas-closet-nextjs-1-145-remove-and-add-links-to-nav-bar
  components/AuthProfileMenu.tsx
  components/Navbar.tsx
Labels: Sprint 1

#138 belinda-nextjs-01-135-add-all-remaining-field
  app/add-product-page/page.module.css
  app/add-product-page/page.tsx
  app/product-page/page.module.css
  app/product-page/page.tsx
  components/AuthProfileMenu.tsx
  components/Input.tsx
  components/InputSelect.tsx
Labels: Sprint 1

#156 belindas-closet-nextjs_1_155_add-mascot-image
  app/auth/sign-in/page.tsx
  app/auth/sign-in/signin-page.module.css
  app/nsc_mascot_green_cropped.png
  package-lock.json
Labels: Sprint 1

#144 Belindas-closet-nextjs-1-153-update-react-query-package
  package-lock.json
  package.json
Labels: Sprint 1

#157 belindas-closet-nextjs_1_176_creators-page-placeholder
  app/creator-page/page.tsx
Labels: enhancement, Sprint 1

#165 Belinda_Android_Sprint_1_164_Delete_Hava_Account_&_Login_Link
  app/auth/sign-up/page.tsx
Labels: Sprint 1

#160 belinda-nextjs-01-175-dynamic-category-routing
  app/category-page/[category]/page.tsx
  app/category-page/page.tsx
  app/home.module.css
  app/page.tsx
  components/CategoryCard.tsx
Labels: Sprint 1

#159 belinda-nextjs-01-158-add_product_function
  app/add-product-page/page.tsx
  app/add-product-page/product-prop-list.tsx
Labels: Sprint 1

#169 belindas-closet-nextjs_1_ 174_donation-info-page-creation
  app/donation-info/page.module.css
  app/donation-info/page.tsx
Labels: Sprint 1

#167 Belindas-closet-nextjs-1-173-update-readme.md
  README.md
Labels: bug, Sprint 1

#184 belindas-closet-nextjs_1_179_product-page
  app/add-product-page/page.module.css
  app/category-page/[categoryId]/page.module.css
  app/category-page/[categoryId]/page.tsx
  app/category-page/[category]/page.tsx
  app/category-page/page.tsx
  app/page.tsx
  package-lock.json
  package.json
Labels: enhancement, Sprint 1

#186 belindas-closet-nextjs_1_183_add-nav-menu-for-product-categories
  components/Navbar.tsx
Labels: Sprint 1

#178 belinda-nextjs-181-admin_page_creation
  app/admin-page/page.tsx
Labels: Sprint 1
