Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2024-07, with the labels that each got.

#466 belindas-closet-nextjs_8_444_display-archived-products
  app/archived-products-page/page.tsx
Labels: enhancement, Sprint 8

#468 belindas-closet-nextjs_8_467_minimized-card
  app/category-page/[categoryId]/page.tsx
  app/category-page/all-products/page.tsx
Labels: enhancement, Sprint 8

#463 belindas-closet-nextjs_8_remove-unrelated-fields_product-detail-page
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
Labels: Sprint 8

#476 belindas-closet-nextjs_9_475-home-mission-donation-page-responsive-ui
  app/donation-info/page.module.css
  app/donation-info/page.tsx
  app/mission-page/page.tsx
  app/page.tsx
Labels: enhancement, Sprint 9

#479 belindas-closet-nextjs_9_478_signup-signin-responsive-pages-responsiv…
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
Labels: enhancement, Sprint 9

#482 belindas-closet-nextjs_9_481_conditionally-render-buttons-on-home-page
  app/page.tsx
Labels: bug, Sprint 9

#484 belindas-closet-nextjs_9_480_remove-unrelated-edit-product-dialog
  components/EditProductDialog.tsx
Labels: bug, Sprint 9

#487 belindas-closet-nextjs_9_485_forgot-change-pw-responsive-ui
  app/auth/change-password-page/page.tsx
  app/auth/forgot-password/page.tsx
Labels: enhancement, Sprint 9

#483 belindas-closet-nextjs_9_477_refactor-nav-bar
  components/AuthProfileMenu.tsx
  components/CategoryDropDownMenu.tsx
  components/Navbar.tsx
Labels: Sprint 9

#489 belindas-closet-nextjs_9_488_category-page-all-products-archived-prod…
  app/archived-products-page/page.tsx
  app/category-page/[categoryId]/page.tsx
  app/category-page/all-products/page.tsx
  components/ProductCard.tsx
Labels: enhancement, Sprint 9

#492 belindas-closet-nextjs_9_490_fix-color-of-links-and-focused-text-fields
  app/theme/themes.tsx
Labels: Sprint 9

#493 belindas-closet-nextjs_9_491_product-detail-page-responsive-ui
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
Labels: enhancement, Sprint 9

#474 belindas-closet-nextjs_9_472_update-creator-page
  app/creator-page/page.tsx
  tests/unit/creator-page/page.test.tsx
Labels: Sprint 9

#494 belindas-closet-nextjs_9_473_update-admin-page
  app/admin-page/page.tsx
  tests/unit/admin-page/admin.test.tsx
Labels: Sprint 9

#498 Bug Fix: fetch logic to display users
  app/edit-user-role-page/page.tsx
  next.config.js
Labels: bug, Sprint 9

#501 belindas-closet-nextjs-500-admin-creator-page-responsive-ui
  app/admin-page/page.tsx
  app/creator-page/page.tsx
  tests/unit/creator-page/page.test.tsx
Labels: enhancement, Sprint 9

#503 belindas-closet-nextjs_10_502_fix-product-detail-error-for-jacket/blazer
  app/category-page/[categoryId]/page.tsx
Labels: Sprint 10

#497 belindas-closet-nextjs_9_496_product-detail-dialogs-responsive-ui
  app/add-product-page/page.module.css
  app/auth/forgot-password/forgot-password-page.module.css
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
  app/globals.css
  components/ConfirmArchiveDialog.tsx
  components/ConfirmDeleteDialog.tsx
  components/EditProductDialog.tsx
  components/Input.tsx
  components/InputFields.tsx
  components/InputSelect.tsx
  styles/Home.module.css
  styles/globals.css
Labels: enhancement, Sprint 9

#508 belindas-closet-nextjs_10_506_fix-redirects-when-signing-in-out
  app/auth/sign-in/page.tsx
  components/AuthProfileMenu.tsx
  components/Navbar.tsx
  hooks/useAuth.tsx
Labels: Sprint 10

#505 belindas-closet-nextjs_10_504_implement-role-based-authorization
  app/add-product-page/page.tsx
  app/admin-page/page.tsx
  app/archived-products-page/page.tsx
  app/creator-page/page.tsx
  app/dashboard/page.tsx
  app/edit-user-role-page/page.tsx
  components/UnauthorizedPageMessage.tsx
  tests/unit/add-product-page/page.test.tsx
  tests/unit/admin-page/admin.test.tsx
  tests/unit/creator-page/page.test.tsx
  tests/unit/dashboard-page/page.test.tsx
Labels: Sprint 10

#507 belindas-closet-nextjs_9_495_update-contact-us-page-material-ui
  app/contact-page/page.tsx
  tests/unit/contact-page/contactpage.test.tsx
Labels: Sprint 9

#509 belindas-closet-nextjs_10_499_profile-page
  app/auth/sign-in/page.tsx
  app/profile/page.tsx
  components/CurrentUserCard.tsx
  components/EditUserDetailsDialog.tsx
Labels: enhancement, Sprint 10

#512 belindas-closet-nextjs_10_510_admin-creator-page-buttons
  app/admin-page/page.tsx
  app/creator-page/page.tsx
Labels: bug, Sprint 10

#518 belindas-closet-nextjs-10_515_buttons-missing-home-page
  app/page.tsx
Labels: bug, Sprint 10

#514 belindas-closet-nextjs_10_513_edit-user-role-page-responsive-ui
  app/edit-user-role-page/page.tsx
  components/EditUserRoleDialog.tsx
Labels: enhancement, Sprint 10

#523 belindas-closet-nextjs_10_522_fix-typos-heading-margin-space
  app/add-product-page/page.tsx
  app/auth/sign-up/page.tsx
  app/contact-page/page.tsx
  app/dashboard/page.tsx
Labels: enhancement, Sprint 10

#521 belindas-closet-nextjs_10_519_restrict-access-profile-change-password…
  app/auth/change-password-page/page.tsx
  app/profile/page.tsx
Labels: enhancement, Sprint 10

#524 belindas-closet-nextjs_10_517_edit-user-role-cancel-button
  components/EditUserRoleDialog.tsx
  components/UserCard.tsx
Labels: enhancement, Sprint 10
