Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2024-05, with the labels that each got.

#330 Belindas closet nextjs 5 300 qa testing 3
  .eslintrc.json
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  tests/mocks/math.ts
  tests/unit/add-product-page/page.test.tsx
  tests/unit/auth/sign-in/page.test.tsx
  tests/unit/auth/sign-up/page.test.tsx
  tests/unit/math.test.ts
  tsconfig.json
Labels: Sprint 5, USER STORY

#316 belindas-closet-nextjs_5_288-327_EditUserRoleDialog-Component-Alert
  components/EditUserRoleDialog.tsx
Labels: enhancement, Sprint 5, USER STORY

#335 belindas-closet-nextjs_5_334_add-a-link-button-to-visualization-dashboard
  app/admin-page/page.tsx
Labels: Sprint 5

#337 Belinda_NextJS_Sprint_6_332_Dashboard_Creator_Link
  app/creator-page/page.tsx
Labels: Sprint 6

#355 belindas-closet-nextjs_6_351_update-product-sizing
  app/add-product-page/product-prop-list.tsx
Labels: Sprint 6

#358 belindas-closet-nextjs_6_354_vary_api_url
  app/add-product-page/page.tsx
  app/auth/change-password-page/page.tsx
  app/auth/reset-password-page/page.tsx
  app/auth/sign-in/page.tsx
  app/auth/sign-up/page.tsx
  app/category-page/[categoryId]/page.tsx
  app/category-page/[categoryId]/products/[productId]/page.tsx
  app/edit-user-role-page/page.tsx
  components/ConfirmArchiveDialog.tsx
  components/ConfirmDeleteDialog.tsx
  components/EditProductDialog.tsx
  components/EditUserRoleDialog.tsx
  components/ProductCard.tsx
  next.config.js
Labels: Sprint 6

#359 belinda-nextjs-6-353-add-auto-update-new-code
  .github/workflows/ssh.yml
Labels: Sprint 6

#366 belindas-closet-nextjs_6_365_edit-user-role-buttons-menu
  components/EditUserRoleDialog.tsx
  components/UserCard.tsx
Labels: enhancement, Sprint 6

#370 Belindas-closet-nextjs_6_369_enable-auto-assign-issues
  .github/workflows/auto-assign-issues.yml
Labels: Sprint 6

#385 belinda-nextjs-6-384-update-cd-with-nvmrc-01
  .github/workflows/ssh.yml
  .nvmrc
Labels: Sprint 6

#342 belindas-closet-nextjs_6_321_mui-admin-page
  app/admin-page/page.tsx
  package-lock.json
  package.json
Labels: enhancement, Sprint 6

#343 belindas-closet-nextjs_6_323_mui-creator-page
  app/creator-page/page.tsx
  package-lock.json
  package.json
Labels: enhancement, Sprint 6

#393 belindas-closet-nextjs_7_392_nav-bar-drop-down-menu
  components/AuthProfileMenu.tsx
Labels: Sprint 7

#377 Belinda_NextJS_Sprint6_Added_Pronoun_Textfield
  app/auth/sign-up/page.tsx
  package-lock.json
Labels: Sprint 6

#399 Removed Dashboard link from navbar for non-admin users
  components/Navbar.tsx
  package-lock.json
  package.json
Labels: Sprint 7

#401 belinda-nextjs-chore-395-add-dark/light-mode
  app/add-product-page/page.tsx
  app/contact-page/page.tsx
  app/dashboard/page.tsx
  app/donation-info/page.tsx
  app/layout.tsx
  app/mission-page/page.tsx
  app/page.tsx
  app/theme/providers.tsx
  app/theme/theme.tsx
  app/theme/themes.tsx
  components/Navbar.tsx
  components/ProductCard.tsx
  components/ThemeToggle.tsx
  components/UserCard.tsx
  components/WrapperDiv.tsx
  package-lock.json
  package.json
  tests/unit/dashboard-page/page.test.tsx
  tests/unit/donation-info/page.test.tsx
Labels: enhancement

#398 Belinda_Next_JS_Sprint_7_386_Fix_Product_Tile_Sizing
  app/category-page/[categoryId]/page.tsx
Labels: Sprint 7

#411 belindas_closet_7_383_qrcode_implementation
  app/qrcode-page/page.tsx
  components/QRCodeGenerator.tsx
  package-lock.json
  package.json
Labels: enhancement

#412 belinda-nextjs-410-add-belinda-designs
  app/category-page/[categoryId]/products/[productId]/ProductDetailDisplay.tsx
  app/favicon.ico
  app/icon.png
  app/logo.png
  app/page.tsx
  components/CategoryImages.tsx
  components/CustomCardContent.tsx
  components/Navbar.tsx
  public/categories-images/accessories.png
  public/categories-images/casual.png
  public/categories-images/dress.png
  public/categories-images/jacket.png
  public/categories-images/pants.png
  public/categories-images/shirt.png
  public/categories-images/shoe.png
  public/categories-images/skirt.png
  public/categories-images/suit.png
Labels: enhancement, Sprint 7
