Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2025-02, with the labels that each got.

#591 belindas-closet-nextjs_Sprint17_558-bug-fix-console-errorwarnings
  components/CategoryBlock.tsx
  components/ImageBanner.tsx
  components/SimpleItemPreview.tsx
  package-lock.json
  package.json
Labels: bug, Sprint 17

#598 Chore: update and rename .env.sample to .env.example
  .env.example
  .env.sample
Labels: Sprint 16

#605 belindas-closet-nextjs-sprint17-fix-empty-carousel-placement-on-homepage
  app/page.tsx
  components/Carousel.tsx
Labels: bug, Sprint 17

#592 Combination: Sprint 16 + Sprint 17
  app/admin-page/page.tsx
  app/category-page/[categoryId]/products/[productId]/page.tsx
  app/contact-page/page.tsx
  app/edit-user-role-page/page.tsx
  app/form-page/page.tsx
  components/ConfirmDeleteUserDialog.tsx
  components/UserCard.tsx
  hooks/useAuth.tsx
  tests/unit/Form-Page/Form-Page.test.tsx
Labels: Sprint 16, Sprint 17
