Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2025-03, with the labels that each got.

#616 belindas-closet-nextjs_20_615_gemini_root_folder_and_config
  .gemini/config.yml
Labels: enhancement

#608 Belindas-closet-nextjs_18_607_Implement_google_analytics_to_the_front-end (nextjs)
  app/layout.tsx
  package-lock.json
  package.json
Labels: enhancement, Sprint 18

#604 Belindas-closet-nextjs_17_603_Created design and filtering logic for product type
  app/category-page/all-products/page.tsx
  app/page.tsx
  components/CategoryDropDownMenu.tsx
  components/Navbar.tsx
  components/productList.tsx
Labels: enhancement, Sprint 18

#620 belindas_closet_sprint_19_issue_619_contact_us_page_container
  app/contact-page/page.tsx
Labels: enhancement, Sprint 19
