Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2025-07, with the labels that each got.

#665 belindas-closet-nextjs_23_662_edit-user-role-page-for-admin-user-management
  app/edit-user-role-page/components/EditUserRoleDialog.tsx
  app/edit-user-role-page/components/UserTable.tsx
  app/edit-user-role-page/models/interface.ts
  app/edit-user-role-page/page.tsx
  hooks/useDebounce.tsx
Labels: enhancement, Sprint 23

#658 belindas-closet_sprint23_issue657_contact-us-page-ui-fix-for-mobile-screens
  app/contact-page/page.tsx
Labels: bug, Sprint 23

#680 Fix/profile api route and UI fixes
  app/profile/page.tsx
  components/AddLookingForDialog.tsx
  tests/unit/contact-page/contactpage.test.tsx
Labels: bug
