Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2025-05, with the labels that each got.

#644 fix: make carousel titles responsive on smaller devices
  .env.example
  app/page.tsx
  components/Carousel.tsx
  components/Navbar.tsx
Labels: bug, Sprint 21

#650 belindas-closet-nextjs_21_649_collapsible-nav
  app/dashboard/page.tsx
  components/DashboardNavbar.tsx
Labels: enhancement, Sprint 21

#645 belindas-closet-nextjs_sprint21_issue637_bugfix-homepage--make-components-match-the-width-of-the-window
  components/Carousel.tsx
Labels: bug, Sprint 21

#647 belindas-closet-nextjs_21_646_sidebar-component-conditioned
  components/Sidebar.tsx
Labels: enhancement, Sprint 21

#653 Bugfix: Remove duplicate return block from CarouselElement component
  components/Carousel.tsx
Labels: bug

#660 659 feature request new navbar design
  app/category-page/all-products/page.tsx
  app/page.tsx
  components/CategoryDropDownMenu.tsx
  components/Navbar.tsx
  components/productList.tsx
Labels: enhancement

#623 belindas-closet-nextjs _21_622_New-profile-page
  app/profile/page.tsx
  components/AddLookingForDialog.tsx
  components/EditUserDetailsDialog.tsx
  components/UserCard.tsx
  components/UserContent.tsx
  components/UserHeader.tsx
  components/UserSideBar.tsx
  types/user.ts
Labels: enhancement

#661 belindas-closet-nextjs_23_655_remove_staging
  .github/workflows/cd.yml
  .github/workflows/staging.yml
  .github/workflows/sync-staging.yml
Labels: Sprint 23

#656 belindas-closet-nextjs_22_654_add-token-based-reset-ui
  app/auth/forgot-password/page.tsx
  app/auth/reset-password-page/page.tsx
  app/auth/reset-password/page.tsx
  components/Carousel.tsx
Labels: enhancement
