Repository SeattleColleges/belindas-closet-nextjs, pull requests merged in 2025-01, with the labels that each got.

#569 belindas-closet-nextjs _567_merge_auto_assign_smartsheets_actions
  .github/workflows/auto-assign-issues.yml
  .github/workflows/on-new-issue.yml
  .github/workflows/on-pull-request.yml
Labels: bug

#575 belindas-closet-nextjs_15_574_post_issue_smartsheet
  post-issue-smartsheet.py
Labels: enhancement

#578 belindas-closet-nextjs _update_post-issue-smartsheet.py
  post-issue-smartsheet.py
Labels: bug

#580 Revert "belindas-closet-nextjs _update_post-issue-smartsheet.py"
  post-issue-smartsheet.py
Labels: bug

#566 belindas-closet-nextjs_15_565_contact-us-page-dependency-update
  app/contact-page/page.tsx
  package-lock.json
  package.json
Labels: bug

#588 belindas-closet-nextjs_sprint16_583_FixHomepage
  app/page.tsx
  package-lock.json
  package.json
Labels: Sprint 16

#590 belindas-closet-nextjs _16_589_actions_adjustments
  .github/workflows/auto-assign-issues.yml
  .github/workflows/on-new-issue.yml
  package-lock.json
  post-issue-smartsheet.py
Labels: bug
